# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/MolCraft',
                'doc_host': 'https://sky1ove.github.io',
                'git_url': 'https://github.com/sky1ove/MolCraft',
                'lib_path': 'MolCraft'},
  'syms': {'MolCraft.core': {'MolCraft.core.foo': ('core.html#foo', 'MolCraft/core.py')}}}
